# Generated by Django 2.2.4 on 2019-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('app_description', models.CharField(blank=True, default='', max_length=400)),
                ('app_link', models.URLField(blank=True, default='https://')),
                ('app_libre', models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1)),
                ('app_usability', models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1)),
                ('app_porting', models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1)),
                ('app_potential', models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1)),
                ('app_design', models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1)),
                ('app_ethic', models.BooleanField(default=False)),
                ('app_used_for_libreadvice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_app_name', models.CharField(max_length=200)),
                ('art_title', models.CharField(max_length=200)),
                ('art_subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('art_abstract', models.CharField(blank=True, default='', max_length=500)),
                ('art_description', models.CharField(blank=True, default='', max_length=280)),
                ('art_link', models.URLField(blank=True, default='')),
                ('art_state', models.CharField(choices=[('TO', 'TODO'), ('WP', 'Work In Progress'), ('DR', 'Drafted'), ('RW', 'Review'), ('TP', 'To Publish'), ('PU', 'Published')], default='TO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pil_art_name', models.CharField(max_length=200)),
                ('pil_name', models.CharField(max_length=200)),
                ('pil_text', models.CharField(blank=True, default='', max_length=280)),
                ('pil_short', models.CharField(blank=True, default='', max_length=200)),
                ('pil_state', models.CharField(choices=[('TO', 'TODO'), ('WP', 'Work In Progress'), ('DR', 'Drafted'), ('RW', 'Review'), ('TP', 'To Publish'), ('PU', 'Published')], default='TO', max_length=2)),
                ('pil_image_url', models.CharField(blank=True, default='https://', max_length=200)),
            ],
        ),
    ]
