# Generated by Django 2.2.4 on 2019-08-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='app_name',
            new_name='app_full_name',
        ),
        migrations.RenameField(
            model_name='pill',
            old_name='pil_art_name',
            new_name='pil_app_name',
        ),
    ]
