# Generated by Django 2.2.4 on 2019-08-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_description',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='app_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
