# Generated by Django 2.2.4 on 2019-08-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0005_auto_20190801_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='art_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
