# Generated by Django 2.2.4 on 2019-08-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0006_articles_art_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
