# Generated by Django 2.2.4 on 2019-08-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0007_auto_20190801_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_libre',
            field=models.CharField(choices=[(1, 'Terrible'), (2, 'Mediocre'), (3, 'Discrete'), (4, 'Good'), (5, 'Excellent')], default=3, max_length=1),
        ),
    ]
