# Generated by Django 2.2.4 on 2019-08-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0008_application_app_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_design',
            field=models.CharField(choices=[(1, 'Terrible'), (2, 'Mediocre'), (3, 'Discrete'), (4, 'Good'), (5, 'Excellent')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='application',
            name='app_porting',
            field=models.CharField(choices=[(1, 'Terrible'), (2, 'Mediocre'), (3, 'Discrete'), (4, 'Good'), (5, 'Excellent')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='application',
            name='app_potential',
            field=models.CharField(choices=[(1, 'Terrible'), (2, 'Mediocre'), (3, 'Discrete'), (4, 'Good'), (5, 'Excellent')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='application',
            name='app_usability',
            field=models.CharField(choices=[(1, 'Terrible'), (2, 'Mediocre'), (3, 'Discrete'), (4, 'Good'), (5, 'Excellent')], default=3, max_length=1),
        ),
    ]
