# Generated by Django 2.2.4 on 2019-08-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0009_auto_20190801_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_ethic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='app_used_for_libreadvice',
            field=models.BooleanField(default=False),
        ),
    ]
