# Generated by Django 2.2.4 on 2019-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0012_auto_20190801_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pil_art_name', models.CharField(max_length=200)),
                ('pil_name', models.CharField(max_length=200)),
                ('pil_text', models.CharField(max_length=280)),
                ('pil_state', models.CharField(choices=[('TO', 'TODO'), ('WP', 'Work In Progress'), ('DR', 'Drafted'), ('RW', 'Review'), ('TP', 'To Publish'), ('PU', 'Published')], default='TO', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='art_abstract',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='art_description',
            field=models.CharField(default='', max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='art_state',
            field=models.CharField(choices=[('TO', 'TODO'), ('WP', 'Work In Progress'), ('DR', 'Drafted'), ('RW', 'Review'), ('TP', 'To Publish'), ('PU', 'Published')], default='TO', max_length=2),
        ),
        migrations.AddField(
            model_name='article',
            name='art_subtitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='app_design',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_libre',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_porting',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_potential',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_usability',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Mediocre'), ('3', 'Discrete'), ('4', 'Good'), ('5', 'Excellent')], default='3', max_length=1),
        ),
    ]
