# Generated by Django 2.2.4 on 2019-08-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0013_auto_20190803_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pills',
            new_name='Pill',
        ),
    ]
