# Generated by Django 2.2.4 on 2019-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0014_auto_20190803_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='pil_text',
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
