# Generated by Django 2.2.4 on 2019-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0015_auto_20190803_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_abstract',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_description',
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_subtitle',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
