# Generated by Django 2.2.4 on 2019-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libredb', '0017_auto_20190803_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_description',
            field=models.CharField(blank=True, default='no description yet', max_length=400),
        ),
    ]
